### ISSUE TITLE
Abbreviations should not be empty

### ISSUE THREAD

**Issue by jmetzmeier** [autokey/autokey-python2#20]
What steps will reproduce the problem?
1. Run 'autokey -l' in terminal.
2. Change focus to any text window (e.g., Mousepad).
3. Type any letter/number.

What is the expected output? What do you see instead?

Autokey should replace configured abbreviations.  Instead, no replacements are made, and even a single letter triggers an exception:

Exception in thread KeypressHandler-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/autokey/iomediator.py", line 204, in run
    target.handle_keypress(rawKey, modifiers, key, windowName, windowClass)
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 179, in handle_keypress
    currentInput, windowInfo, True)
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 304, in __checkTextMatches
    if item.check_input(buffer, windowInfo):
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 735, in check_input
    abbr = self._should_trigger_abbreviation(buffer)
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 134, in _should_trigger_abbreviation
    if self.__checkInput(buffer, abbr):
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 147, in __checkInput
    stringBefore, typedAbbr, stringAfter = self._partition_input(buffer, abbr)
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 189, in _partition_input
    stringBefore, typedAbbr, stringAfter = matchString.rpartition(abbr)
ValueError: empty separator

What version of the product are you using? On what operating system?

Autokey 0.90.4, KDE 4.8.5, Xubuntu 12.04

Please provide any additional information below.

Full command-line log attached.  To obtain this, I ran 'autokey -l', clicked on an open Mousepad window, and typed the letter 'a', then exited Autokey normally.

Sep 26, 2012 #1 justin.y...@gmail.com
OK, found the problem.  I had accidentally entered a _blank_ abbreviation for a given phrase.  Since it was blank, I didn't see it in the abbreviations window, and the only way I noticed (besides knowing how rpartition() can throw a ValueError) was that the list of abbreviations was '[question,question,]': there was an extra comma at the end.

It might be a good idea to notify the user if he/she has entered an empty abbreviation, or disallow it altogether.

Migrated from: https://code.google.com/p/autokey/issues/detail?id=219

**Comment by FromCrimsonToWool** [comment]
I just had this same issue today.  Sure enough, I had to track down a pesky empty abbreviation.  I'm running autokey-gtk version 0.90.4 on Korora( Fedora 24 ), and I installed it from the Fedora repo.

**Comment by josephj11** [comment]
It doesn't show it here, but I was the first to report this one. I lost the use of AutoKey for around a year until I tracked it down. It was fixed by Jordan. If you still have it, you are not using the latest (slightly better) version of AutoKey 0.91.1 which is available here. See [https://github.com/autokey/autokey/wiki/Installing-from-GitHub](https://github.com/autokey/autokey/wiki/Installing-from-GitHub)

If you need further assistance, please visit us at
[https://github.com/autokey/autokey/wiki/Installing-from-GitHub](https://groups.google.com/forum/#!forum/autokey-users)

I just tried to duplicate the problem on my install from repositories on kubuntu 16.04 and could not.
